apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
  - image: devops_helper_bot_dev
profiles:
  - name: dev
    deploy:
      kubeContext: minikube
      kustomize:
        paths: 
          - "k8s/environments/dev"