---

shared:
  root_url: https://github.com/Asgoret/devops_chats/blob/master/
  relocate_filename: relocate.md
  coc_filename: CoC.md
  jobs_filename: vacancy.md
  advertising_filename: ad.md
  othet_chats: Friendly_chats.md
  events_list: events.md
  course_folder: courses
  course_filename: courses.md
  hrman_filename: hrman.md

"-1001051806860":  # DevOps Jobs
  # User commands list
  ## Sharing knolewge commands
  starter: true
  middle: true
  cert: true
  relocate: true
  course: true
  tasks: true
  hrman: true
  ## Rules commands
  coc: true
  work: true
  ad: true
  chats: true
  events: true
  ## Other commands
  report: true
  summon: true
  # Admin commands list
  mute: true
  warn: false
  unwarn: false
  move: true
  man: true
  job: true
  # Service commands
  delete_service_message: true
  # Variables
  ## Variables for command 'job'
  job_rss: "@devops_jobs_feed @sre_devops_jobs_rss"
  ## Variable for command 'man'
  commands_list: devops_jobs
  ## Variable for commands 'starter\middle\certification'
  study: devops
  certification_filename: certification.md
  starter_filename: starter.md
  middle_filename: middle.md
  ## Variables for command 'move'
  move_to_id: -1001030317489
  move_to_name: "@devops_ru"
  move_from_id: -1001051806860
  ## Variable for command 'summon'
  summon_list: "@sofiko_mh @pomeha_sprava @arunova @railyakaM @hope_dies_last_HR"
  ## Variable for command 'report'
  admin_chat: -1001180815953
  # Variable for command 'tasks'
  github_url: https://github.com/Asgoret/test_tasks

"-1001030317489":  # DevOps Ru
  # User commands list
  ## Sharing knolewge commands
  starter: true
  middle: true
  cert: true
  relocate: true
  course: true
  tasks: true
  hrman: false
  ## Rules commands
  coc: true
  work: false
  ad: true
  chats: true
  events: true
  ## Other commands
  report: true
  summon: false
  # Admin commands list
  mute: true
  warn: false
  unwarn: false
  move: true
  man: true
  job: false
  # Service commands
  delete_service_message: true
  # Variables
  ## Variable for command 'man'
  commands_list: devops_ru
  ## Variable for commands 'starter\middle\certification'
  study: devops
  certification_filename: certification.md
  starter_filename: starter.md
  middle_filename: middle.md
  ## Variables for command 'move'
  move_to_id: -1001051806860
  move_to_name: "@devops_jobs"
  move_from_id: -1001030317489
  ## Variable for command 'report'
  admin_chat: -1001180815953
  # Variable for command 'tasks'
  github_url: https://github.com/Asgoret/test_tasks

"-1001180815953":  # DevOps Admin chat
  # User commands list
  ## Sharing knolewge commands
  starter: false
  middle: false
  cert: false
  relocate: false
  course: false
  tasks: false
  hrman: false
  ## Rules commands
  coc: false
  work: false
  ad: false
  chats: false
  events: false
  ## Other commands
  report: false
  summon: false
  # Admin commands list
  mute: false
  warn: false
  unwarn: false
  move: false
  man: true
  job: false
  # Service commands
  delete_service_message: false
  # Variables
  ## Variable for command 'man'
  commands_list: devops_admin

"-1001112614954":  # TelRan++
  # User commands list
  ## Sharing knolewge commands
  starter: true
  middle: true
  cert: true
  relocate: true
  course: true
  tasks: true
  hrman: false
  ## Rules commands
  coc: true
  work: true
  ad: false
  chats: false
  events: false
  ## Other commands
  report: false
  summon: false
  # Admin commands list
  mute: true
  warn: false
  unwarn: false
  move: false
  man: true
  job: true
  # Service commands
  delete_service_message: false
  # Variables
  ## Variable for command 'man'
  commands_list: telran
  ## Variable for commands 'starter\middle\certification'
  study: devops
  certification_filename: certification.md
  starter_filename: starter.md
  middle_filename: middle.md
  ## Variables for command 'job'
  job_rss: "@israjobs"


### SRE Hamster project
"-1001354992135":  # SRE Hamster Job
  # User commands list
  ## Sharing knolewge commands
  starter: true
  middle: true
  cert: true
  relocate: true
  course: true
  tasks: true
  hrman: true
  ## Rules commands
  coc: true
  work: true
  ad: true
  chats: true
  events: true
  ## Other commands
  report: true
  summon: false
  # Admin commands list
  mute: true
  warn: false
  unwarn: false
  move: true
  man: true
  job: true
  # Service commands
  delete_service_message: true
  # Variables
  ## Variables for command 'job'
  job_rss: "@sre_devops_jobs_rss"
  ## Variable for command 'man'
  commands_list: devops_jobs
  ## Variable for commands 'starter\middle\certification'
  study: devops
  certification_filename: certification.md
  starter_filename: starter.md
  middle_filename: middle.md
  ## Variables for command 'move'
  move_to_id: -1001299585988
  move_to_name: "@sre_hamster_tech"
  move_from_id: -1001354992135
  ## Variable for command 'summon'
  summon_list: "@Asgoret"
  ## Variable for command 'report'
  admin_chat: -372303704
  # Variable for command 'tasks'
  github_url: https://github.com/Asgoret/test_tasks

"-1001299585988":  # SRE Hamster Tech
  # User commands list
  ## Sharing knolewge commands
  starter: true
  middle: true
  cert: true
  relocate: true
  course: true
  tasks: true
  hrman: false
  ## Rules commands
  coc: true
  work: false
  ad: true
  chats: true
  events: true
  ## Other commands
  report: true
  summon: false
  # Admin commands list
  mute: true
  warn: false
  unwarn: false
  move: true
  man: true
  job: false
  jobs: false
  # Service commands
  delete_service_message: true
  # Variables
  ## Variable for command 'man'
  commands_list: devops_jobs
  ## Variable for commands 'starter\middle\certification'
  study: devops
  certification_filename: certification.md
  starter_filename: starter.md
  middle_filename: middle.md
  ## Variables for command 'move'
  move_to_id: -1001354992135
  move_to_name: "@sre_hamster_job"
  move_from_id: -1001299585988
  ## Variable for command 'report'
  admin_chat: -372303704
  # Variable for command 'tasks'
  github_url: https://github.com/Asgoret/test_tasks
