---

name: Style checks with editorconfig-checker

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches-ignore: []

jobs:
  build:
    name: Run editorconfig-checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: editorconfig-checker/action-editorconfig-checker@v1
