# https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python?langId=py

---

name: Python best-practices

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install black flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --show-source --statistics

      - name: Lint with Black
        run: |
          black . --check --diff
